# Generated by Django 3.1.7 on 2021-04-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teammates',
            fields=[
                ('TeammateId', models.AutoField(primary_key=True, serialize=False)),
                ('TeammateName', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('JoinDate', models.DateField()),
                ('ProfilePicPath', models.CharField(max_length=300)),
            ],
        ),
    ]
